-- ====================================================================
--          DEFINITIVE DUMMY DATA CLEANUP SCRIPT
-- ====================================================================
-- This script safely removes all data generated by the 'generate_dummy_analytics.sql'
-- script. It targets data using specific naming patterns to avoid accidental deletion
-- of real user data.
-- ====================================================================

DO $$
DECLARE
    v_deleted_count INT;
BEGIN
    RAISE NOTICE 'Starting definitive dummy data cleanup...';

    -- 1. Delete Dummy Orders
    DELETE FROM public.crm_orders 
    WHERE order_number LIKE 'ORD-DUMMY-%';
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % dummy orders.', v_deleted_count;

    -- 2. Delete Dummy Activities
    -- (Linked to dummy clients or dummy messages, plus explicit patterns)
    DELETE FROM public.crm_activities
    WHERE client_id IN (SELECT id FROM public.crm_clients WHERE company_name LIKE 'Dummy Corp %' OR company_name LIKE 'Dummy User %')
       OR message_id IN (
           SELECT m.id FROM public.messages m 
           JOIN public.contacts c ON m.contact_id = c.id 
           WHERE c.name LIKE 'Dummy User %'
       )
       OR subject LIKE 'AI Message on %'
       OR description LIKE 'AI response %'
       OR description LIKE 'User message %'
       OR description LIKE 'Agent response %';
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % dummy activities.', v_deleted_count;

    -- 3. Delete Dummy Deal History
    DELETE FROM public.crm_deal_stages_history
    WHERE deal_id IN (SELECT id FROM public.crm_deals WHERE name LIKE 'Dummy Deal %');
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % dummy deal history records.', v_deleted_count;

    -- 4. Delete Dummy Deals
    DELETE FROM public.crm_deals 
    WHERE name LIKE 'Dummy Deal %';
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % dummy deals.', v_deleted_count;

    -- 5. Delete Dummy Clients
    DELETE FROM public.crm_clients 
    WHERE company_name LIKE 'Dummy Corp %' 
       OR company_name LIKE 'Dummy User %';
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % dummy clients.', v_deleted_count;

    -- 6. Delete Dummy Messages
    DELETE FROM public.messages 
    WHERE contact_id IN (
        SELECT id FROM public.contacts 
        WHERE name LIKE 'Dummy User %'
    );
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % dummy messages.', v_deleted_count;

    -- 7. Delete Dummy Contacts
    DELETE FROM public.contacts 
    WHERE name LIKE 'Dummy User %';
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % dummy contacts.', v_deleted_count;

    -- 8. Delete Dummy Channel
    DELETE FROM public.channels 
    WHERE name = 'Dummy Data Channel' OR platform_channel_id = 'dummy_whatsapp_123';
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % dummy channels.', v_deleted_count;

    -- 9. Refresh Analytics Views to clear the charts
    PERFORM public.refresh_all_analytics();
    RAISE NOTICE 'Analytics views refreshed. Charts should now be empty.';

END $$;
